app_bundle:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /


  

  
  
# FOS User bundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile
    

    
fos_user_registration_confirmed:
    path:      /{_locale}/register/confirmed
    defaults:  { _controller: AppBundle:User:afterLogin}  
    

    
#    <route id="fos_user_registration_confirm" path="/confirm/{token}" methods="GET">
#        <default key="_controller">fos_user.registration.controller:confirmAction</default>
#    </route>