admin_business_index:
    path:     /
    defaults: { _controller: "AppBundle:Business:index" }
    methods:  GET

admin_business_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Business:show" }
    methods:  GET

admin_business_new:
    path:     /new
    defaults: { _controller: "AppBundle:Business:new" }
    methods:  [GET, POST]

admin_business_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Business:edit" }
    methods:  [GET, POST]

admin_business_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Business:delete" }
    methods:  DELETE
