admin_sponsor_index:
    path:     /
    defaults: { _controller: "AppBundle:Sponsor:index" }
    methods:  GET

admin_sponsor_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Sponsor:show" }
    methods:  GET

admin_sponsor_new:
    path:     /new
    defaults: { _controller: "AppBundle:Sponsor:new" }
    methods:  [GET, POST]

admin_sponsor_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Sponsor:edit" }
    methods:  [GET, POST]

admin_sponsor_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Sponsor:delete" }
    methods:  DELETE
