homepage:
    path:      /index
    defaults:  { _controller: "AppBundle:Default:index" }


comming_soon:
    path:      /
    defaults:  { _controller: "AppBundle:Default:commingSoon"}

app_admin_business:
    resource: "@AppBundle/Resources/config/routing/business.yml"
    prefix:   /admin_business

