app_admin_business:
    resource: "@AppBundle/Resources/config/routing/business.yml"
    prefix:   /admin_business

app_admin_speaker:
    resource: "@AppBundle/Resources/config/routing/speaker.yml"
    prefix:   /admin_speaker

app_admin_photo:
    resource: "@AppBundle/Resources/config/routing/photo.yml"
    prefix:   /admin_photo
        
app_admin_sponsor:
    resource: "@AppBundle/Resources/config/routing/sponsor.yml"
    prefix:   /admin_sponsor
    
    
app_admin_fos_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /admin_fos_user
    
    
app_admin_job:
    resource: "@AppBundle/Resources/config/routing/job.yml"
    prefix:   /admin_job
    


#homepage:
#    path:      /
#    defaults:  { _controller: "AppBundle:Default:index" }
#    
#homepage_year:
#    path:      /{year}
#    defaults:  { _controller: "AppBundle:Default:index" }


homepage:
    path:      /{_locale}/{year}
    defaults:  { _controller: AppBundle:Default:index, _locale: pt, year: 2019 }
    requirements:
        year:  2018|2019
        _locale:  en|pt

        
after_login_route_name:
    path:      /after_login
    defaults:  { _controller: AppBundle:User:afterLogin}

        
                
        
        
editUser:
    path:      /{_locale}/{year}/{user}
    defaults:  { _controller: AppBundle:Default:editUser, _locale: pt, year: 2019 }
    requirements:
        year:  2018|2019
        _locale:  en|pt
        
        
                


comming_soon:
    path:      /comming_soon
    defaults:  { _controller: "AppBundle:Default:commingSoon"}



